version: "3.7"
x-env: &defaults
  NODE_ENV: development
  NODE_PATH:
  DB_NAME:
  MONGODB_HOST:
  MONGODB_PASSWORD:
  MONGODB_USERNAME:
  REACT_APP_BACKEND_URL:
  REACT_APP_ASSET_URL:
services:
  mongo:
    container_name: photo-sharing-mongo
    image: photo-sharing/db
    build:
      context: db/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./mongo_data
        target: /data/db
      - type: bind
        source: ./db
        target: /opt/db
    ports:
      - 27017:27017
    environment: *defaults
  web:
    stdin_open: true
    container_name: photo-sharing-web
    image: photo-sharing/web
    build:
      context: web/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./web
        target: /opt/app
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 128000000
    ports:
      - 2015:2015

    depends_on:
      - api
    environment:
      PORT: 2015
      <<: *defaults
    command: >
      bash -c "npm run dev"

  api:
    container_name: photo-sharing-api
    image: photo-sharing/api
    build:
      context: api/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /opt/app
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 128000000
    ports:
      - 5001:5001
      - 9228:9228

    depends_on:
      - mongo
    environment:
      <<: *defaults
      PORT: 5001
    command: >
      bash -c "sleep 5 && npm run dev:docker"
