const jwt                   = require('jsonwebtoken');
var SECRET                  = process.env.SECRET || 'defaultSecret';
const HttpError             = require('../model/httpErrors');
const defaultLog            =require('../../logger');

/**
 *      For accessing the API a valid JWT token must be passed in all the queries in
     the 'Authorization' header.
     A valid JWT token is generated by the API and returned as answer of a call
     to the route /login giving a valid user & password.
     The following syntax must be used in the 'Authorization' header :
         Bearer xxxxxx.yyyyyyy.zzzzzz
 */
module.exports = (req, res, next) => {
	if (req.method === 'OPTIONS') {
		return next();
	}
	try {
		const token = req.headers.authorization.split(' ')[1]; // Authorization: 'Bearer TOKEN'
		// console.log('do I have token?               ', token);
		if (!token) {
			throw new Error('Authentication failed!');
		}
		const decodedToken = jwt.verify(token, SECRET);
		// console.log('guess I am here', decodedToken);
		req.userData = { userId: decodedToken.userId };
		next();
	} catch (err) {
		const error = new HttpError('Authentication failed!', 403);
		defaultLog.errorLog.info('Error:', err);
		return next(error);
	}
};
