apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: photo-sharing
    deployment: photo-sharing-web
  name: photo-sharing-web-env
data:
  environment.js: |
    // set some defaults here
    window.REACT_APP_BACKEND_URL = "https://photo-sharing-api-bcb254-dev.apps.clab.devops.gov.bc.ca"
    window.REACT_APP_ASSET_URL = "https://photo-sharing-api-bcb254-dev.apps.clab.devops.gov.bc.ca/api"