apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bcb254-dev
bases:
  - ../../base/mongo
patches:
  - mongo-env-patch.yaml
generatorOptions:
  labels:
    app: photo-sharing
    type: generated
configMapGenerator:
  - name: mongodb-env
    env: mongodb.properties
secretGenerator:
- name: photo-sharing-mongo-creds
  envs:
  - .env.secret
  files:
  - MONGODB_KEYFILE_VALUE
images:
  - name: mongo
    newName: image-registry.openshift-image-registry.svc:5000/bcgov/mongodb-36-ha 
    newTag: "1"