---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongodb
  labels:
    app: photo-sharing
spec:
  template:
    spec:
      containers:
        - name: mongo-container
          envFrom: 
          - configMapRef:
              name: mongodb-env
          - secretRef:
              name: photo-sharing-mongo-creds